### ISSUE TITLE
Dependency on bounds for block fill. Is it necessary?

### ISSUE THREAD

**Issue by bnlawrence** [ajheaps/cf-view#6]
This code
```python
import cf
import cfplot as cfp
#
# script generated by cfgui version 0.0.1
#
                    #
dataset=cf.read('../../Data/ggap199006200600.nc')
#
fields=[dataset[i] for i in [9]]
sfield=fields[0]
kwargs={}
kwargs['dim2']=cf.wi(-89.1415,89.1415)
kwargs['dim3']=cf.wi(0.0,358.875)
kwargs['dim0']=cf.wi(0.0,0.0)
kwargs['dim1']=cf.wi(1.0,1000.0)
sfield=sfield.subspace(**kwargs)
plotOptions={'mapset': {'proj': 'cyl'}, 'gopen': {'rows': 1, 'columns': 2}, 'nup': 2,
 'con': {'colorbar': None, 'blockfill': 1, 'fill': None, 'ylog': None, 'negative_line
style': None, 'xlog': None, 'colorbar_orientation': None, 'lines': None, 'ptype': Non
e, 'line_labels': True}}
cfp.gopen(**plotOptions['gopen'])
plotOptions['con']['title']=sfield.file
cfp.gpos(1)
plotOptions['con']['title']=' long_name:p:1000.0 '
slicer={'dim1': 1000.0}
cfp.con(sfield.subspace(**slicer),**plotOptions['con'])
```
generates the error
```
python2.7 debug.py 
Traceback (most recent call last):
  File "debug.py", line 24, in <module>
    cfp.con(sfield.subspace(**slicer),**plotOptions['con'])
  File "/usr/lib/python2.7/site-packages/cfplot/cfplot.py", line 312, in con
    if f[0].coord('lon').isbounded:
AttributeError: 'DimensionCoordinate' object has no attribute 'isbounded'
```

**Comment by ajheaps** [comment]
Closed as this no longer occurs as per previous comment.
